server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sqllotto
    username: lotto
    password: sadang
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#               (create, create-drop, validate, update)    
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect : org.hibernate.dialect.PostgreSQLDialect
        temp : 
          use_jdbc_metadata_defaults: false
  mvc:
    view:
      prefix: /resources/templates/dynamic
      suffix: .html

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace